// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type Night struct {
	NightDate    string        `json:"night_date"`
	Decision     string        `json:"decision"`
	Score        int64         `json:"score"`
	Reason       string        `json:"reason"`
	Source       string        `json:"source"`
	CloudSummary string        `json:"cloud_summary"`
	RainSummary  string        `json:"rain_summary"`
	HourlyJson   string        `json:"hourly_json"`
	DuskAt       int64         `json:"dusk_at"`
	DawnAt       int64         `json:"dawn_at"`
	MoonRiseAt   sql.NullInt64 `json:"moon_rise_at"`
	MoonSetAt    sql.NullInt64 `json:"moon_set_at"`
	MoonIllumPct float64       `json:"moon_illum_pct"`
	NotifiedAt   sql.NullInt64 `json:"notified_at"`
	CreatedAt    int64         `json:"created_at"`
	UpdatedAt    int64         `json:"updated_at"`
	Imaged       sql.NullInt64 `json:"imaged"`
	ImageResult  string        `json:"image_result"`
	ImageUrl     string        `json:"image_url"`
	NinaJson     string        `json:"nina_json"`
}
