// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nights.sql

package store

import (
	"context"
	"database/sql"
)

const getNight = `-- name: GetNight :one
SELECT night_date, decision, score, reason, source, cloud_summary, rain_summary, hourly_json, dusk_at, dawn_at, moon_rise_at, moon_set_at, moon_illum_pct, notified_at, created_at, updated_at, imaged, image_result, image_url, nina_json FROM nights WHERE night_date = ?
`

func (q *Queries) GetNight(ctx context.Context, nightDate string) (Night, error) {
	row := q.db.QueryRowContext(ctx, getNight, nightDate)
	var i Night
	err := row.Scan(
		&i.NightDate,
		&i.Decision,
		&i.Score,
		&i.Reason,
		&i.Source,
		&i.CloudSummary,
		&i.RainSummary,
		&i.HourlyJson,
		&i.DuskAt,
		&i.DawnAt,
		&i.MoonRiseAt,
		&i.MoonSetAt,
		&i.MoonIllumPct,
		&i.NotifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Imaged,
		&i.ImageResult,
		&i.ImageUrl,
		&i.NinaJson,
	)
	return i, err
}

const listNights = `-- name: ListNights :many
SELECT night_date, decision, score, reason, source, cloud_summary, rain_summary, hourly_json, dusk_at, dawn_at, moon_rise_at, moon_set_at, moon_illum_pct, notified_at, created_at, updated_at, imaged, image_result, image_url, nina_json FROM nights ORDER BY night_date DESC LIMIT ? OFFSET ?
`

type ListNightsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListNights(ctx context.Context, arg ListNightsParams) ([]Night, error) {
	rows, err := q.db.QueryContext(ctx, listNights, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Night
	for rows.Next() {
		var i Night
		if err := rows.Scan(
			&i.NightDate,
			&i.Decision,
			&i.Score,
			&i.Reason,
			&i.Source,
			&i.CloudSummary,
			&i.RainSummary,
			&i.HourlyJson,
			&i.DuskAt,
			&i.DawnAt,
			&i.MoonRiseAt,
			&i.MoonSetAt,
			&i.MoonIllumPct,
			&i.NotifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Imaged,
			&i.ImageResult,
			&i.ImageUrl,
			&i.NinaJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNightsBefore = `-- name: ListNightsBefore :many
SELECT night_date, decision, score, reason, source, cloud_summary, rain_summary, hourly_json, dusk_at, dawn_at, moon_rise_at, moon_set_at, moon_illum_pct, notified_at, created_at, updated_at, imaged, image_result, image_url, nina_json FROM nights WHERE night_date < ? ORDER BY night_date DESC LIMIT ?
`

type ListNightsBeforeParams struct {
	NightDate string `json:"night_date"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListNightsBefore(ctx context.Context, arg ListNightsBeforeParams) ([]Night, error) {
	rows, err := q.db.QueryContext(ctx, listNightsBefore, arg.NightDate, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Night
	for rows.Next() {
		var i Night
		if err := rows.Scan(
			&i.NightDate,
			&i.Decision,
			&i.Score,
			&i.Reason,
			&i.Source,
			&i.CloudSummary,
			&i.RainSummary,
			&i.HourlyJson,
			&i.DuskAt,
			&i.DawnAt,
			&i.MoonRiseAt,
			&i.MoonSetAt,
			&i.MoonIllumPct,
			&i.NotifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Imaged,
			&i.ImageResult,
			&i.ImageUrl,
			&i.NinaJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markImaged = `-- name: MarkImaged :exec
UPDATE nights
SET imaged = ?, image_result = ?, image_url = ?, updated_at = ?
WHERE night_date = ?
`

type MarkImagedParams struct {
	Imaged      sql.NullInt64 `json:"imaged"`
	ImageResult string        `json:"image_result"`
	ImageUrl    string        `json:"image_url"`
	UpdatedAt   int64         `json:"updated_at"`
	NightDate   string        `json:"night_date"`
}

func (q *Queries) MarkImaged(ctx context.Context, arg MarkImagedParams) error {
	_, err := q.db.ExecContext(ctx, markImaged,
		arg.Imaged,
		arg.ImageResult,
		arg.ImageUrl,
		arg.UpdatedAt,
		arg.NightDate,
	)
	return err
}

const setNightNina = `-- name: SetNightNina :exec
UPDATE nights SET nina_json = ?, updated_at = ? WHERE night_date = ?
`

type SetNightNinaParams struct {
	NinaJson  string `json:"nina_json"`
	UpdatedAt int64  `json:"updated_at"`
	NightDate string `json:"night_date"`
}

func (q *Queries) SetNightNina(ctx context.Context, arg SetNightNinaParams) error {
	_, err := q.db.ExecContext(ctx, setNightNina, arg.NinaJson, arg.UpdatedAt, arg.NightDate)
	return err
}

const setNightNotified = `-- name: SetNightNotified :exec
UPDATE nights SET notified_at = ?, updated_at = ? WHERE night_date = ?
`

type SetNightNotifiedParams struct {
	NotifiedAt sql.NullInt64 `json:"notified_at"`
	UpdatedAt  int64         `json:"updated_at"`
	NightDate  string        `json:"night_date"`
}

func (q *Queries) SetNightNotified(ctx context.Context, arg SetNightNotifiedParams) error {
	_, err := q.db.ExecContext(ctx, setNightNotified, arg.NotifiedAt, arg.UpdatedAt, arg.NightDate)
	return err
}

const upsertNight = `-- name: UpsertNight :exec
INSERT INTO nights (
  night_date, decision, score, reason, source,
  cloud_summary, rain_summary, hourly_json,
  dusk_at, dawn_at, moon_rise_at, moon_set_at, moon_illum_pct,
  created_at, updated_at
) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
ON CONFLICT(night_date) DO UPDATE SET
  decision       = excluded.decision,
  score          = excluded.score,
  reason         = excluded.reason,
  source         = excluded.source,
  cloud_summary  = excluded.cloud_summary,
  rain_summary   = excluded.rain_summary,
  hourly_json    = excluded.hourly_json,
  dusk_at        = excluded.dusk_at,
  dawn_at        = excluded.dawn_at,
  moon_rise_at   = excluded.moon_rise_at,
  moon_set_at    = excluded.moon_set_at,
  moon_illum_pct = excluded.moon_illum_pct,
  updated_at     = excluded.updated_at
`

type UpsertNightParams struct {
	NightDate    string        `json:"night_date"`
	Decision     string        `json:"decision"`
	Score        int64         `json:"score"`
	Reason       string        `json:"reason"`
	Source       string        `json:"source"`
	CloudSummary string        `json:"cloud_summary"`
	RainSummary  string        `json:"rain_summary"`
	HourlyJson   string        `json:"hourly_json"`
	DuskAt       int64         `json:"dusk_at"`
	DawnAt       int64         `json:"dawn_at"`
	MoonRiseAt   sql.NullInt64 `json:"moon_rise_at"`
	MoonSetAt    sql.NullInt64 `json:"moon_set_at"`
	MoonIllumPct float64       `json:"moon_illum_pct"`
	CreatedAt    int64         `json:"created_at"`
	UpdatedAt    int64         `json:"updated_at"`
}

// Insert or overwrite a night's decision + snapshot. Keyed by night_date, so a
// re-run for the same date updates the row rather than inserting a duplicate.
// created_at and notified_at are preserved on conflict.
func (q *Queries) UpsertNight(ctx context.Context, arg UpsertNightParams) error {
	_, err := q.db.ExecContext(ctx, upsertNight,
		arg.NightDate,
		arg.Decision,
		arg.Score,
		arg.Reason,
		arg.Source,
		arg.CloudSummary,
		arg.RainSummary,
		arg.HourlyJson,
		arg.DuskAt,
		arg.DawnAt,
		arg.MoonRiseAt,
		arg.MoonSetAt,
		arg.MoonIllumPct,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
