// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	GetNight(ctx context.Context, nightDate string) (Night, error)
	ListNights(ctx context.Context, arg ListNightsParams) ([]Night, error)
	ListNightsBefore(ctx context.Context, arg ListNightsBeforeParams) ([]Night, error)
	MarkImaged(ctx context.Context, arg MarkImagedParams) error
	SetNightNina(ctx context.Context, arg SetNightNinaParams) error
	SetNightNotified(ctx context.Context, arg SetNightNotifiedParams) error
	// Insert or overwrite a night's decision + snapshot. Keyed by night_date, so a
	// re-run for the same date updates the row rather than inserting a duplicate.
	// created_at and notified_at are preserved on conflict.
	UpsertNight(ctx context.Context, arg UpsertNightParams) error
}

var _ Querier = (*Queries)(nil)
