// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscribers.sql

package store

import (
	"context"
	"database/sql"
)

const confirmSubscriber = `-- name: ConfirmSubscriber :execresult
UPDATE subscribers SET confirmed_at = ?, updated_at = ?
WHERE token = ? AND confirmed_at IS NULL
`

type ConfirmSubscriberParams struct {
	ConfirmedAt sql.NullInt64 `json:"confirmed_at"`
	UpdatedAt   int64         `json:"updated_at"`
	Token       string        `json:"token"`
}

func (q *Queries) ConfirmSubscriber(ctx context.Context, arg ConfirmSubscriberParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, confirmSubscriber, arg.ConfirmedAt, arg.UpdatedAt, arg.Token)
}

const countSubscribers = `-- name: CountSubscribers :one
SELECT COUNT(*) FROM subscribers
`

func (q *Queries) CountSubscribers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubscribers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubscriber = `-- name: CreateSubscriber :exec
INSERT INTO subscribers (email, discord_webhook, token, last_sent_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSubscriberParams struct {
	Email          string `json:"email"`
	DiscordWebhook string `json:"discord_webhook"`
	Token          string `json:"token"`
	LastSentAt     int64  `json:"last_sent_at"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
}

func (q *Queries) CreateSubscriber(ctx context.Context, arg CreateSubscriberParams) error {
	_, err := q.db.ExecContext(ctx, createSubscriber,
		arg.Email,
		arg.DiscordWebhook,
		arg.Token,
		arg.LastSentAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteSubscriberByToken = `-- name: DeleteSubscriberByToken :execresult
DELETE FROM subscribers WHERE token = ?
`

func (q *Queries) DeleteSubscriberByToken(ctx context.Context, token string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteSubscriberByToken, token)
}

const getSubscriberByEmail = `-- name: GetSubscriberByEmail :one
SELECT id, email, discord_webhook, token, confirmed_at, last_sent_at, created_at, updated_at FROM subscribers WHERE email = ?
`

func (q *Queries) GetSubscriberByEmail(ctx context.Context, email string) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, getSubscriberByEmail, email)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DiscordWebhook,
		&i.Token,
		&i.ConfirmedAt,
		&i.LastSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriberByToken = `-- name: GetSubscriberByToken :one
SELECT id, email, discord_webhook, token, confirmed_at, last_sent_at, created_at, updated_at FROM subscribers WHERE token = ?
`

func (q *Queries) GetSubscriberByToken(ctx context.Context, token string) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, getSubscriberByToken, token)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DiscordWebhook,
		&i.Token,
		&i.ConfirmedAt,
		&i.LastSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConfirmedSubscribers = `-- name: ListConfirmedSubscribers :many
SELECT id, email, discord_webhook, token, confirmed_at, last_sent_at, created_at, updated_at FROM subscribers WHERE confirmed_at IS NOT NULL ORDER BY id
`

func (q *Queries) ListConfirmedSubscribers(ctx context.Context) ([]Subscriber, error) {
	rows, err := q.db.QueryContext(ctx, listConfirmedSubscribers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriber
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DiscordWebhook,
			&i.Token,
			&i.ConfirmedAt,
			&i.LastSentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeStalePending = `-- name: PurgeStalePending :exec
DELETE FROM subscribers WHERE confirmed_at IS NULL AND updated_at < ?
`

// Sign-ups that never confirmed. Purged so an abused form cannot fill the table.
// updated_at, not created_at: a re-submission rotates the token and restarts the clock.
func (q *Queries) PurgeStalePending(ctx context.Context, updatedAt int64) error {
	_, err := q.db.ExecContext(ctx, purgeStalePending, updatedAt)
	return err
}

const refreshPendingSubscriber = `-- name: RefreshPendingSubscriber :exec
UPDATE subscribers
SET discord_webhook = ?, token = ?, last_sent_at = ?, updated_at = ?
WHERE email = ? AND confirmed_at IS NULL
`

type RefreshPendingSubscriberParams struct {
	DiscordWebhook string `json:"discord_webhook"`
	Token          string `json:"token"`
	LastSentAt     int64  `json:"last_sent_at"`
	UpdatedAt      int64  `json:"updated_at"`
	Email          string `json:"email"`
}

// A re-submission for an address that has not confirmed yet: take the newest webhook,
// rotate the token so the older confirmation link stops working, and restamp last_sent_at.
func (q *Queries) RefreshPendingSubscriber(ctx context.Context, arg RefreshPendingSubscriberParams) error {
	_, err := q.db.ExecContext(ctx, refreshPendingSubscriber,
		arg.DiscordWebhook,
		arg.Token,
		arg.LastSentAt,
		arg.UpdatedAt,
		arg.Email,
	)
	return err
}

const touchSubscriberSent = `-- name: TouchSubscriberSent :exec
UPDATE subscribers SET last_sent_at = ?, updated_at = ? WHERE id = ?
`

type TouchSubscriberSentParams struct {
	LastSentAt int64 `json:"last_sent_at"`
	UpdatedAt  int64 `json:"updated_at"`
	ID         int64 `json:"id"`
}

func (q *Queries) TouchSubscriberSent(ctx context.Context, arg TouchSubscriberSentParams) error {
	_, err := q.db.ExecContext(ctx, touchSubscriberSent, arg.LastSentAt, arg.UpdatedAt, arg.ID)
	return err
}
